services:
  # 1. Redis Cache & Broker Service
  redis-broker:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    # FIX LAYER: Host mode connectivity for stable networking namespaces
    network_mode: "host"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. FastAPI Web Application
  web-app:
    build: .
    container_name: fastapi_container
    restart: always
    network_mode: "host" # Container direct host routing use karega
    env_file: [.env]
    depends_on:
      redis-broker: { condition: service_healthy }

  # 3. Celery Worker Service
  celery-worker:
    build: .
    container_name: celery_worker_container
    restart: always
    network_mode: "host" # Direct server system connection trace use karega
    env_file: [.env]
    depends_on:
      redis-broker: { condition: service_healthy }

  # 4. Celery Beat Service
  # celery-beat:
  #   build: .
  #   container_name: celery_beat_container
  #   restart: always
  #   network_mode: "host"
  #   env_file: [.env]
  #   depends_on:
  #     redis-broker: { condition: service_healthy }

volumes:
  redis_data:
