"""create blacklist user token table

Revision ID: 0b566065d8b9
Revises: 5fecf4d33c4c
Create Date: 2026-06-16 19:50:06.425320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b566065d8b9'
down_revision: Union[str, Sequence[str], None] = '5fecf4d33c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user_blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('jti_access', sa.String(length=50), nullable=True),
    sa.Column('jti_refresh', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['account_users.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti_refresh'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_account_user_blacklist_tokens_user_uid'), 'account_user_blacklist_tokens', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_blacklist_tokens_user_uid'), table_name='account_user_blacklist_tokens')
    op.drop_table('account_user_blacklist_tokens')
    # ### end Alembic commands ###
