"""upgrade blacklist table

Revision ID: 35b2e1259597
Revises: 0b566065d8b9
Create Date: 2026-06-16 21:33:49.353079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b2e1259597'
down_revision: Union[str, Sequence[str], None] = '0b566065d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user_blacklist_tokens', sa.Column('jti_token', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('account_user_blacklist_tokens_jti_refresh_key'), 'account_user_blacklist_tokens', type_='unique')
    op.drop_column('account_user_blacklist_tokens', 'jti_access')
    op.drop_column('account_user_blacklist_tokens', 'jti_refresh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user_blacklist_tokens', sa.Column('jti_refresh', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('account_user_blacklist_tokens', sa.Column('jti_access', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('account_user_blacklist_tokens_jti_refresh_key'), 'account_user_blacklist_tokens', ['jti_refresh'], postgresql_nulls_not_distinct=False)
    op.drop_column('account_user_blacklist_tokens', 'jti_token')
    # ### end Alembic commands ###
