"""upgrade password filed name in user table

Revision ID: 5fecf4d33c4c
Revises: 60fbb410fa32
Create Date: 2026-06-16 10:06:21.978582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fecf4d33c4c'
down_revision: Union[str, Sequence[str], None] = '60fbb410fa32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('hashed_password', sa.String(length=200), nullable=True))
    op.drop_column('account_users', 'pashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('pashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('account_users', 'hashed_password')
    # ### end Alembic commands ###
