"""add password filed in user table

Revision ID: 60fbb410fa32
Revises: 65d23fe41e19
Create Date: 2026-06-16 10:05:18.499840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fbb410fa32'
down_revision: Union[str, Sequence[str], None] = '65d23fe41e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_users', sa.Column('pashed_password', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_users', 'pashed_password')
    # ### end Alembic commands ###
