"""upgrade blacklist table unique jti

Revision ID: 939004f98f79
Revises: 35b2e1259597
Create Date: 2026-06-16 21:43:46.119201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939004f98f79'
down_revision: Union[str, Sequence[str], None] = '35b2e1259597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_user_blacklist_tokens', 'jti_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'account_user_blacklist_tokens', ['jti_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_user_blacklist_tokens', type_='unique')
    op.alter_column('account_user_blacklist_tokens', 'jti_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
